### ISSUE TITLE
postgresql not working

### ISSUE THREAD

**Issue by cosminadrianpopescu** [cosminadrianpopescu/vim-sql-workbench#9]
Apparently the postgresql is not working. This is because `SQL Workbench/J` returns other strings on commands sent which do not get parsed correctly by `sqlwbserver` script. See issue #1 for this.

**Comment by cosminadrianpopescu** [comment]
Fixed with release 3.0. Please use for the moment `SQL Workbench/J` build 116, not 117.

**Comment by sluedtke** [comment]
Sorry, its me again. 

I works much better but still not as expected:
- I have to keep the "server.vim" file you send to me vial mail. 
- the results of the screenshot I put into #1 are now all displayed into the split buffer, the sql query as well 
- the status of the `SWDbExplorer` remains, I get results of the public schema in the server window, but nothing more. The server window does not respond anymore, even though I was waiting for 1-2 minutes

I used the 116 build of sql-workbench/J and started the server in an external terminal.

**Comment by cosminadrianpopescu** [comment]
> I have to keep the "server.vim" file you send to me vial mail. 

If you installed the last version, it should be the same file. Are you sure you have the last version? You can delete the repository and do again a git clone (if you installed with `pathogen`)

> the results of the screenshot I put into #1 are now all displayed into the split buffer, the sql query as well 

So you can run queries, right? You only have a problem with `dbexplorer`?

> the status of the SWDbExplorer remains, I get results of the public schema in the server window, but nothing more. The server window does not respond anymore, even though I was waiting for 1-2 minutes

I am not sure I understand this 100%. So you do `SWDbExplorerOpen crop_db 5000`, you get the results on the screen (your list of tables) and then you can't control `vim` again? if this is true, could you please send the output from the debug `sqlwbserver` window (the one from terminal)? If this is not true, then could you please explain again what is happening? 

Thank you.

**Comment by cosminadrianpopescu** [comment]
> I have to keep the "server.vim" file you send to me vial mail. 

Sorry, actually you are right. I forgot to commit that. I will make this evening a 3.1.1 release which will include that.

**Comment by sluedtke** [comment]
Here we go! I made a screenshot of the entire session includding the command history (`SWExecuteCurrent` was called 3 times). 

I did `ctrl+ c` in the server window, because vim was not responding any more after waiting some time. The DB explorer  tab in vim was oppened, both lower columns of that were empty. 

When I was moving back to the sql tab, I got plenty of messages, all  of this session are listed below:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test.sql" [New] 4L, 61C written
"test.sql" [New] 4L, 61C written
"test.sql" 4L, 61C
Processing a command. Please wait...
Processing a command. Please wait...
--No lines in buffer--
Processing a command. Please wait...
--No lines in buffer--
Error detected while processing function sw#dbexplorer#show_panel..<SNR>141_set_highlights:
line    2:
E419: FG color unknown
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   54:
Traceback (most recent call last):
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   54:
  File "<string>", line 9, in <module>
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   54:
  File "/usr/lib/python2.7/socket.py", line 224, in meth
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   54:
    return getattr(self._sock,name)(*args)
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   54:
socket.error: [Errno 111] Connection refused
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   55:
E121: Undefined variable: result
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   55:
E116: Invalid arguments for function len(result) <= 3
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   55:
E15: Invalid expression: len(result) <= 3
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   58:
E121: Undefined variable: result
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   58:
E116: Invalid arguments for function substitute(result, '\r', '', 'g')
Error detected while processing function sw#sqlwindow#check_results..sw#server#fetch_result..<SNR>1
33_pipe_execute:
line   58:
E15: Invalid expression: substitute(result, '\r', '', 'g')       

```

The results you see in the server window are only from the public scheme, the others are not listed. We do have a rather big table in the **data** scheme. Not sure whether that might cause problems, it does not in sql-workbench/J.

**Comment by sluedtke** [comment]
forgot the screenshot :-)

![screenshot2](https://cloud.githubusercontent.com/assets/5367675/7211279/a580b248-e559-11e4-9024-4fe5d55c41f7.png)

**Comment by cosminadrianpopescu** [comment]
Could you please try do download the 3.1.1 version from [here](http://www.vim.org/scripts/script.php?script_id=5081). I will also make the 3.1.1 available on `github` tonight, but until then, you can download it from www.vim.org. 

Hopefully this will fix all the `postgresql` problems. Thank you for your help in fixing it. As usual, please let me know if it's not working. 

I am not closing the ticket yet. I will be waiting for confirmation that it works.

**Comment by sluedtke** [comment]
Hi, 
this looks better. After some seconds, gvim is back and I got the DBExplorer TAB. Great!
What do I have do I have to do to see the content of **all** schemas of that DB. Right now, I do only see the _public_ one?!

**Comment by cosminadrianpopescu** [comment]
You need to create profiles (either from the `SQL Workbench/J` GUI, either by using the `wbconnect` and then `wbstoreprofile`) which point to your database (there is a database option in the GUI). Once the profile is created, you can do `SWDbExplorer [profileName] [port]` to connect to the database you want.

**Comment by sluedtke** [comment]
I think that what I have done:

![screenshot3](https://cloud.githubusercontent.com/assets/5367675/7247473/3524808e-e80a-11e4-90e4-4d509d378765.png)

The first line says "The current profile is crop_db", that is the connection profile I created in the GUI and I am using SWDbExplorer to connect with 

```
SWSqlConnectToServer 5000 
SWDbExplorer crop_db 5000
```

**Comment by cosminadrianpopescu** [comment]
So it means I didn't understood exactly. It's probably something specific for postgresql. The way oracle or mysql or sqlserver work is that I select a profile, I select a database and that's it. I use that database. If I want another database, I create another profile and open another `dbexplorer` with another database. 

Do you know the commands that you would need to send to change the schema? If you know the commands, you can extend the `dbexplorer` (see docs). 

Anyway, if you give me the commands to change the schema, I can tell you what you need to do to extend the `dbexplorer` to include those.

**Comment by sluedtke** [comment]
I think that is indeed different to other DB's. I only worked with MySQL before, nothing like that exists there. It is basically a layer between the DB and the  tables that is most often used to group tables  by theme.  So I write:

```
SELECT * FROM data.rt_crops;
```

where data is schema. 

Within the GUI, there is a drop down menu to select the specific schema or all `*`. So it is implemented within the sql-workbench/J  GUI.

**Comment by cosminadrianpopescu** [comment]
So, when you connect with the profile `crop_db`, what schema is used? Is it possible to have a dump of your schema so I can test? Because I've never used `postgresql` before? If it is confidential, could you point me to some schemas that I could download from internet which meet your requirements to test? Because if you do

```
select * from data.rt_crops;
```

to me it sound that you should have a profile for the schema `data`. And then, if you want to run

```
select * from another_data.another_rt_crops;
```

you should have another profile for the schema `another_data`. But probably I am missing something.

**Comment by sluedtke** [comment]
Connecting via your plugin, the _public_ schema is used. Within the GUI, I can select and indicate that the GUI remembers the schema I left on quit, that will be used on start up. 

All those schemas exist within the same DB instance. The default schema, and the only one that exists after creating  a new DB is called **public**. 

![screenshot4](https://cloud.githubusercontent.com/assets/5367675/7248208/5a117b5c-e811-11e4-9ac8-765cc2e56d6c.png)

Maybe the screenshot helps.

In pgadmin3, you can simply create a new schema within the context menu  of the _Schema(x)_ entry (where x is the number of available schemas). 

Within the screenshot I sent before, next to the **DATABASE** column is actually a column called **SCHEMA** that has _public_ as entries.

**Comment by cosminadrianpopescu** [comment]
By default, do I have this kind of structure in `postgresql`. Do you have a dump of a database with a similar structure so I can test?

**Comment by sluedtke** [comment]
I will send you a dummy DB with different schemas and no data. Do you think that is enough for testing?

**Comment by cosminadrianpopescu** [comment]
Yes. Thank you. I will do the testing and let you know how to extend your database explorer.

**Comment by cosminadrianpopescu** [comment]
To extend your `dbexplorer` to include the schemas options, you need to add this in your `vimrc`: 

```
call sw#dbexplorer#add_tab('*', 'Show schemas','M', 'wblistschemas;', [{'title': 'Select schema', 'shortcut': 'H', 'command': "set search_path to %object%;"}, {'title': 'Select *', 'shortcut': 'A', 'command': "set search_path to '*.*'"}])
```

After this, when you want to change the schema, click `M`. Then if you want to select a schema, just go with the cursor on top of it and click `H`. If you want to select all schemas (`*`), just go with the cursor on top of any schema and click `A`. 

Then you can click `O` again and you should see the objects of the new schema. 

Please note that this does not include the schemas `information_schema` and `pg_catalog`. I don't know how to fetch those from `psql`. If you also need those, please let me know which is the psql command to list them and I will try to give you the line to add in `vimrc`. 

Please let me know how it works.

**Comment by sluedtke** [comment]
So this works almost as expected ;-).  
The schema of the DB are listed and an can browse them. 

By now, not all shortcuts are working because,  the `SELECT * FROM` statement does not include the schema name. For the test DB, the correct queries are:

`SELECT * FROM data.table2`
and 
`SELECT * FROM spatial.table3`
of course this refers to the _D_ for Data, the _C_ for columns does not work as well. 

Thanks!

![screenshot5](https://cloud.githubusercontent.com/assets/5367675/7269335/4e63c798-e8d3-11e4-8e20-091c450b6067.png)

**Comment by cosminadrianpopescu** [comment]
Ok, I will also fix this at home. For this I will need to create a new release, because I need to add an option to have the schema prefixing the tables in the commands.

**Comment by cosminadrianpopescu** [comment]
Fixed in the 3.2 release. Download this new release, and then please use the `resources/dbexplorer-postgresql.vim` database explorer. You can do this either by replacing the `resources/dbexplorer.vim` file with this one, either by setting the `g:sw_dbexplorer_panel` variable to point to the `resources/dbexplorer-postgresql.vim`. 

Please let me know how it works.
